import json

from datadiff.issue_readiness import (
    ALREADY_SUBMITTED_OR_CONFIRMED,
    NEEDS_DEDUP_CHECK,
    NEEDS_REPRODUCER_OR_EVIDENCE,
    NOT_LATEST_REPRODUCIBLE,
    READY_TO_SUBMIT,
    build_issue_readiness,
    render_issue_readiness_markdown,
    write_issue_readiness_outputs,
)


def _issue_body(*, title: str, status: str, extra: str = "") -> str:
    return f"""# {title}

## Discovery Record

| Item | Value |
| --- | --- |
| Project family labels observed | `sample_family@pyarrow` |
| First recorded live signal | 2026-05-26 10:00:00 CST |
| How found | DataDiffFuzz differential and metamorphic oracle found a stable mismatch |
| Status | {status} |

## Environment

```text
pyarrow: 24.0.0
```

## Reproducer

```python
print("minimal")
```

## Actual Output

```text
wrong
```

## Expected Output

```text
right
```

## DataDiffFuzz Evidence

- Generated by project code from a latest-version run.

{extra}
"""


def test_build_issue_readiness_classifies_submission_queue(tmp_path):
    latest = tmp_path / "latest_confirmations.json"
    latest.write_text(
        json.dumps(
            {
                "confirmations": [
                    {
                        "family": "confirmed_family@datafusion",
                        "issue_url": "https://github.com/apache/datafusion/issues/1",
                        "upstream_status": "upstream_labeled_bug",
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    new_issue = tmp_path / "new_issue"
    generated = new_issue / "generated"
    old_issue = tmp_path / "old_issue"
    generated.mkdir(parents=True)
    old_issue.mkdir()
    (old_issue / "README.md").write_text("https://github.com/apache/arrow/issues/99\n", encoding="utf-8")
    (generated / "manifest.json").write_text(
        json.dumps({"candidate_bug_families": ["sample_family@pyarrow"]}),
        encoding="utf-8",
    )

    (new_issue / "ready.md").write_text(
        _issue_body(
            title="Ready Issue",
            status="New candidate issue, not yet submitted upstream",
            extra="## Duplicate Search\n\nNo obvious exact duplicate was found.",
        ),
        encoding="utf-8",
    )
    (new_issue / "dedup.md").write_text(
        _issue_body(
            title="Dedup Issue",
            status="New candidate issue; needs final upstream dedup check before counting as confirmed",
        ),
        encoding="utf-8",
    )
    (new_issue / "old_known.md").write_text(
        _issue_body(
            title="Old Known Mention",
            status="New candidate issue, not yet submitted upstream",
            extra="Related old issue: https://github.com/apache/arrow/issues/99",
        ),
        encoding="utf-8",
    )
    (new_issue / "missing.md").write_text(
        "# Missing Evidence\n\n| Item | Value |\n| --- | --- |\n| Status | New candidate issue, not yet submitted upstream |\n",
        encoding="utf-8",
    )
    (new_issue / "flaky.md").write_text(
        _issue_body(
            title="Flaky Reproducer",
            status="Needs stable reproducer; repeated issue-bundle attempts are flaky",
        ),
        encoding="utf-8",
    )
    (new_issue / "submitted.md").write_text(
        _issue_body(
            title="Submitted Issue",
            status="Upstream issue open, labeled bug",
            extra="https://github.com/apache/datafusion/issues/1",
        ).replace("sample_family@pyarrow", "confirmed_family@datafusion"),
        encoding="utf-8",
    )
    (new_issue / "not_latest.md").write_text(
        _issue_body(
            title="Not Latest",
            status="Historical local candidate; not reproduced on latest version",
        ),
        encoding="utf-8",
    )

    audit = build_issue_readiness(
        latest_confirmation_files=[latest],
        new_issue_dir=new_issue,
        old_issue_dir=old_issue,
        generated_issue_dir=generated,
    )

    by_name = {item["path"].split("/")[-1]: item for item in audit["issues"]}
    assert by_name["ready.md"]["readiness_status"] == READY_TO_SUBMIT
    assert by_name["dedup.md"]["readiness_status"] == NEEDS_DEDUP_CHECK
    assert by_name["old_known.md"]["readiness_status"] == NEEDS_DEDUP_CHECK
    assert by_name["missing.md"]["readiness_status"] == NEEDS_REPRODUCER_OR_EVIDENCE
    assert by_name["flaky.md"]["readiness_status"] == NEEDS_REPRODUCER_OR_EVIDENCE
    assert "flaky" in by_name["flaky.md"]["blocking_reasons"][0]
    assert by_name["submitted.md"]["readiness_status"] == ALREADY_SUBMITTED_OR_CONFIRMED
    assert by_name["submitted.md"]["safe_for_paper_confirmed_count"] is True
    assert by_name["not_latest.md"]["readiness_status"] == NOT_LATEST_REPRODUCIBLE
    assert audit["summary"]["ready_to_submit_count"] == 1
    assert audit["summary"]["ready_to_submit_family_count"] == 1
    assert audit["summary"]["needs_dedup_check_count"] == 2
    assert audit["summary"]["needs_dedup_check_family_count"] == 1
    assert audit["summary"]["needs_reproducer_or_evidence_count"] == 2
    assert audit["summary"]["needs_reproducer_or_evidence_family_count"] == 2
    assert audit["summary"]["confirmed_count_eligible_count"] == 1
    assert audit["summary"]["confirmed_count_eligible_family_count"] == 1
    assert audit["summary"]["submission_group_count"] == 1
    assert audit["summary"]["submission_group_families"] == ["sample_family@pyarrow"]
    assert audit["summary"]["submission_groups_ready_to_submit_count"] == 1
    assert audit["summary"]["submission_groups_needs_dedup_count"] == 1
    assert audit["summary"]["duplicate_family_draft_count"] == 2
    ready_path = str((new_issue / "ready.md").resolve())
    dedup_path = str((new_issue / "dedup.md").resolve())
    old_known_path = str((new_issue / "old_known.md").resolve())
    assert audit["summary"]["duplicate_family_draft_groups"] == {
        "sample_family@pyarrow": [
            ready_path,
            dedup_path,
            old_known_path,
        ]
    }
    assert audit["submission_groups"] == [
        {
            "family": "sample_family@pyarrow",
            "issue_count": 3,
            "issue_paths": [
                ready_path,
                dedup_path,
                old_known_path,
            ],
            "needs_dedup_check": True,
            "primary_issue_path": ready_path,
            "primary_title": "Ready Issue",
            "priority": "high",
            "priority_score": 96,
            "status_counts": {
                NEEDS_DEDUP_CHECK: 2,
                READY_TO_SUBMIT: 1,
            },
            "submission_status": READY_TO_SUBMIT,
            "supporting_issue_paths": [
                dedup_path,
                old_known_path,
            ],
        }
    ]


def test_issue_readiness_can_include_generated_drafts(tmp_path):
    new_issue = tmp_path / "new_issue"
    generated = new_issue / "generated"
    old_issue = tmp_path / "old_issue"
    generated.mkdir(parents=True)
    old_issue.mkdir()
    (new_issue / "manual.md").write_text(
        _issue_body(title="Manual", status="New candidate issue, not yet submitted upstream"),
        encoding="utf-8",
    )
    (generated / "raw.md").write_text(
        _issue_body(title="Generated", status="New candidate issue generated by automated project code"),
        encoding="utf-8",
    )

    default_audit = build_issue_readiness(new_issue_dir=new_issue, old_issue_dir=old_issue, generated_issue_dir=generated)
    generated_audit = build_issue_readiness(
        new_issue_dir=new_issue,
        old_issue_dir=old_issue,
        generated_issue_dir=generated,
        include_generated=True,
    )

    assert default_audit["summary"]["issue_document_count"] == 1
    assert generated_audit["summary"]["issue_document_count"] == 2
    assert any(item["source"] == "generated" for item in generated_audit["issues"])
    generated_item = next(item for item in generated_audit["issues"] if item["source"] == "generated")
    assert generated_item["readiness_status"] == NEEDS_REPRODUCER_OR_EVIDENCE
    assert "raw generated draft" in generated_item["blocking_reasons"][0]


def test_issue_readiness_prefers_aligned_audit_family_over_early_live_label(tmp_path):
    new_issue = tmp_path / "new_issue"
    generated = new_issue / "generated"
    old_issue = tmp_path / "old_issue"
    generated.mkdir(parents=True)
    old_issue.mkdir()
    (generated / "manifest.json").write_text(
        json.dumps({"candidate_bug_families": ["polars_vector_division_rounding@polars"]}),
        encoding="utf-8",
    )
    (new_issue / "polars_vector_division_rounding.md").write_text(
        _issue_body(
            title="Vector Division",
            status="New candidate issue, not yet submitted upstream",
        ).replace("sample_family@pyarrow", "grouped_topk_null_sort_key@polars,polars_lazy"),
        encoding="utf-8",
    )

    audit = build_issue_readiness(new_issue_dir=new_issue, old_issue_dir=old_issue, generated_issue_dir=generated)

    assert audit["issues"][0]["family_guess"] == "polars_vector_division_rounding@polars"


def test_write_issue_readiness_outputs_writes_json_and_markdown(tmp_path):
    audit = {
        "schema_version": "issue-readiness-v1",
        "generated_at": "2026-05-26T12:00:00Z",
        "summary": {
            "ready_to_submit_count": 1,
            "needs_dedup_check_count": 0,
            "needs_reproducer_or_evidence_count": 0,
            "already_submitted_or_confirmed_count": 0,
            "not_latest_reproducible_count": 0,
        },
        "issues": [
            {
                "path": "new_issue/ready.md",
                "readiness_status": READY_TO_SUBMIT,
                "priority": "high",
                "blocking_reasons": [],
            }
        ],
    }

    json_path, md_path = write_issue_readiness_outputs(audit, output_dir=tmp_path)

    assert json_path.name == "issue-readiness-20260526T120000.json"
    assert md_path.name == "issue-readiness-20260526T120000.md"
    assert json.loads(json_path.read_text(encoding="utf-8"))["schema_version"] == "issue-readiness-v1"
    markdown = render_issue_readiness_markdown(audit)
    assert "DataDiffFuzz Issue Readiness" in markdown
    assert "Submission Groups" in markdown
    assert "`new_issue/ready.md`" in md_path.read_text(encoding="utf-8")
