"""Single import surface for the frozen OSC public interface."""

from __future__ import annotations

from datadiff_osc.contract_engine import (
    ApplicabilityCertificate,
    DerivationCertificate,
    Endpoint,
    HyperContract,
    Observation,
    ObservationCertificate,
    RelationObligation,
    SchemaField,
    Verdict,
)
from datadiff_osc.schemas import (
    AtomProvenance,
    ContractFingerprint,
    CoverageLevel,
    EvidenceEnvelope,
    EvidenceState,
    EvidenceTier,
    ExecutionStatus,
    FailureKind,
    InfeasibleConstructionEvidence,
    LedgerEvent,
    ResourceTokens,
    ResultGroup,
    RuntimeCacheKey,
    SeedLineage,
    SeedStage,
    SemanticAtom,
    StagedComparisonRequest,
    StagedComparisonResult,
    StructuredExecutionOutcome,
    TargetFingerprint,
    TaskIdentity,
    TaskKind,
    TaskSpec,
    VerdictKind,
)
from datadiff_osc.semantic_targets.model import (
    ActivationCertificate,
    BackendPairObligation,
    CompiledTargetUniverse,
    ContrastEdge,
    ContrastSet,
    InteractionTile,
    ProvenanceClass,
    TargetAssignment,
    TargetCell,
    TargetTemplate,
)


PUBLIC_API_SCHEMA_VERSION = "osc-public-api-freeze-v1"

# This is intentionally explicit: consumers and the freeze test use it to
# reject duplicate model definitions in owned implementation directories.
PUBLIC_SYMBOL_SOURCES = {
    "ActivationCertificate": "datadiff_osc.semantic_targets.model",
    "ApplicabilityCertificate": "datadiff_osc.contract_engine.applicability",
    "AtomProvenance": "datadiff_osc.schemas",
    "BackendPairObligation": "datadiff_osc.semantic_targets.model",
    "CompiledTargetUniverse": "datadiff_osc.semantic_targets.model",
    "ContractFingerprint": "datadiff_osc.schemas",
    "ContrastEdge": "datadiff_osc.semantic_targets.model",
    "ContrastSet": "datadiff_osc.semantic_targets.model",
    "CoverageLevel": "datadiff_osc.schemas",
    "DerivationCertificate": "datadiff_osc.contract_engine.derivation",
    "Endpoint": "datadiff_osc.contract_engine.model",
    "EvidenceEnvelope": "datadiff_osc.schemas",
    "EvidenceState": "datadiff_osc.schemas",
    "EvidenceTier": "datadiff_osc.schemas",
    "ExecutionStatus": "datadiff_osc.schemas",
    "FailureKind": "datadiff_osc.schemas",
    "InfeasibleConstructionEvidence": "datadiff_osc.schemas",
    "HyperContract": "datadiff_osc.contract_engine.model",
    "InteractionTile": "datadiff_osc.semantic_targets.model",
    "LedgerEvent": "datadiff_osc.schemas",
    "Observation": "datadiff_osc.contract_engine.model",
    "ObservationCertificate": "datadiff_osc.contract_engine.evidence",
    "ProvenanceClass": "datadiff_osc.semantic_targets.model",
    "RelationObligation": "datadiff_osc.contract_engine.model",
    "ResourceTokens": "datadiff_osc.schemas",
    "ResultGroup": "datadiff_osc.schemas",
    "RuntimeCacheKey": "datadiff_osc.schemas",
    "SchemaField": "datadiff_osc.contract_engine.model",
    "SeedLineage": "datadiff_osc.schemas",
    "SeedStage": "datadiff_osc.schemas",
    "SemanticAtom": "datadiff_osc.schemas",
    "StagedComparisonRequest": "datadiff_osc.schemas",
    "StagedComparisonResult": "datadiff_osc.schemas",
    "StructuredExecutionOutcome": "datadiff_osc.schemas",
    "TargetAssignment": "datadiff_osc.semantic_targets.model",
    "TargetCell": "datadiff_osc.semantic_targets.model",
    "TargetFingerprint": "datadiff_osc.schemas",
    "TargetTemplate": "datadiff_osc.semantic_targets.model",
    "TaskIdentity": "datadiff_osc.schemas",
    "TaskKind": "datadiff_osc.schemas",
    "TaskSpec": "datadiff_osc.schemas",
    "Verdict": "datadiff_osc.contract_engine.model",
    "VerdictKind": "datadiff_osc.schemas",
}


__all__ = [
    "ActivationCertificate",
    "ApplicabilityCertificate",
    "AtomProvenance",
    "BackendPairObligation",
    "CompiledTargetUniverse",
    "ContractFingerprint",
    "ContrastEdge",
    "ContrastSet",
    "CoverageLevel",
    "DerivationCertificate",
    "Endpoint",
    "EvidenceEnvelope",
    "EvidenceState",
    "EvidenceTier",
    "ExecutionStatus",
    "FailureKind",
    "InfeasibleConstructionEvidence",
    "HyperContract",
    "InteractionTile",
    "LedgerEvent",
    "Observation",
    "ObservationCertificate",
    "PUBLIC_API_SCHEMA_VERSION",
    "PUBLIC_SYMBOL_SOURCES",
    "ProvenanceClass",
    "RelationObligation",
    "ResourceTokens",
    "ResultGroup",
    "RuntimeCacheKey",
    "SchemaField",
    "SeedLineage",
    "SeedStage",
    "SemanticAtom",
    "StagedComparisonRequest",
    "StagedComparisonResult",
    "StructuredExecutionOutcome",
    "TargetAssignment",
    "TargetCell",
    "TargetFingerprint",
    "TargetTemplate",
    "TaskIdentity",
    "TaskKind",
    "TaskSpec",
    "Verdict",
    "VerdictKind",
]
